// The platform layer every page talks through.
export * as app from './app'
export * as clipboard from './clipboard'
export * as dialog from './dialog'
export * as events from './events'
export * as paths from './paths'
export * as session from './session'
export * as shell from './shell'
export * as state from './state'
export { capabilities, useCapabilities } from './host'
export { rpc, stream, RpcError } from './rpc'
export { rcClient, rcFetch, rcUrl } from './rc'
