// The platform layer every page talks through. One import surface, the same on the desktop
// (whose windows are served by the embedded server) and in a browser tab.
export * as app from './app'
export * as clipboard from './clipboard'
export * as dialog from './dialog'
export * as events from './events'
export * as fs from './fs'
export * as os from './os'
export * as paths from './paths'
export * as session from './session'
export * as shell from './shell'
export * as state from './state'
export * as windows from './windows'
export { capabilities, useCapabilities } from './host'
export { rpc, stream, RpcError } from './rpc'
export { rcClient, rcFetch, rcUrl } from './rc'
